/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaProblemas.java
 *
 * Created on 26/11/2010, 02:06:37
 */

package gui;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.Timer;
import javax.swing.UIManager;
import org.pushingpixels.substance.api.skin.SubstanceNebulaLookAndFeel;

/**
 *
 * @author Felipe
 */
public class TelaProblemas extends javax.swing.JFrame {
    
    Timer timer;

    /** Creates new form TelaProblemas */
    public TelaProblemas() {
        setTimer();
        initComponents();
        setWindowPos();
    }

    public void checarCaixasDeSelecao(){
        if (rouboPerda.isSelected()){
            amassadosGraves.setEnabled(false);
            arranhoes.setEnabled(false);
            amassadosLeves.setEnabled(false);
        }else{
            amassadosGraves.setEnabled(true);
            arranhoes.setEnabled(true);
            amassadosLeves.setEnabled(true);
        }
    }

    private void setWindowPos() {
        Dimension dimension = this.getToolkit().getScreenSize();
        int x = (int) (dimension.getWidth() - this.getSize().getWidth()) / 2;
        int y = (int) (dimension.getHeight() - this.getSize().getHeight()) / 2;
        this.setLocation(x, y);
        URL url = this.getClass().getResource("/images/icon2.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    private void setTimer() {
        ActionListener action = new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                checarCaixasDeSelecao();
            }
        };
        this.timer = new Timer(500, action);
        this.timer.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arranhoes = new javax.swing.JCheckBox();
        amassadosLeves = new javax.swing.JCheckBox();
        amassadosGraves = new javax.swing.JCheckBox();
        rouboPerda = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selecione os problemas");
        setResizable(false);

        arranhoes.setText("Arranhões");

        amassadosLeves.setText("Amassados Leves");

        amassadosGraves.setText("Amassados Graves");

        rouboPerda.setText("Roubo / Perda Total");

        jButton1.setText("OK");
        jButton1.setDoubleBuffered(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arranhoes)
                    .addComponent(amassadosGraves))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amassadosLeves)
                    .addComponent(rouboPerda))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButton1)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amassadosGraves)
                        .addGap(3, 3, 3)
                        .addComponent(arranhoes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amassadosLeves)
                        .addGap(3, 3, 3)
                        .addComponent(rouboPerda)))
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new SubstanceNebulaLookAndFeel());
                } catch (Exception e) {
                    System.out.println("Falha ao carregar a skin!");
                }
                new TelaProblemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox amassadosGraves;
    private javax.swing.JCheckBox amassadosLeves;
    private javax.swing.JCheckBox arranhoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox rouboPerda;
    // End of variables declaration//GEN-END:variables

}
